//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaction()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string transactions_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> user_id { get; set; }
        public string username { get; set; }
        public string phonenumber { get; set; }
        public string gmail { get; set; }
        public string address { get; set; }
        public Nullable<int> total_price { get; set; }
        public string payment { get; set; }
        public string payment_info { get; set; }
        public string message { get; set; }
        public string security { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> shipping { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
